services:
  - type: web
    name: portfolio-rag-chatbot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NVIDIA_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
